name: Backpack Cloud
description: "Ideas worth packing!"

encoding: utf-8

highlighter: rouge

paginate: 15
paginate_path: :num

permalink: date

exclude:
  - test
  - .sass-cache

url: https://www.backpackcloud.com

plugins:
  - jekyll-paginate
  - i18n
  - closure-compiler
  - sass
